Repository kubevirt/web-ui-operator, pull requests merged in 2019-03, with the labels that each got.

#27 Add V2VVMWare CRD during web-ui deployment
  build/kubevirt-web-ui-ansible/roles/kubevirt_web_ui/defaults/main.yml
  build/kubevirt-web-ui-ansible/roles/kubevirt_web_ui/files/kubevirt_v1alpha1_v2vvmware_crd.yaml
  build/kubevirt-web-ui-ansible/roles/kubevirt_web_ui/tasks/deprovision.yml
  build/kubevirt-web-ui-ansible/roles/kubevirt_web_ui/tasks/provision.yml
Labels: size/S

#28 Add vmware-to-kubevirt-os.yaml
  build/kubevirt-web-ui-ansible/roles/kubevirt_web_ui/defaults/main.yml
  build/kubevirt-web-ui-ansible/roles/kubevirt_web_ui/files/vmware-to-kubevirt-os.yaml
  build/kubevirt-web-ui-ansible/roles/kubevirt_web_ui/tasks/deprovision.yml
  build/kubevirt-web-ui-ansible/roles/kubevirt_web_ui/tasks/provision.yml
Labels: size/L

#30 Add service ca
  build/kubevirt-web-ui-ansible/roles/kubevirt_web_ui/defaults/main.yml
  build/kubevirt-web-ui-ansible/roles/kubevirt_web_ui/files/console-template.yaml
  build/kubevirt-web-ui-ansible/roles/kubevirt_web_ui/files/service_ca_config.yaml
  build/kubevirt-web-ui-ansible/roles/kubevirt_web_ui/tasks/deprovision.yml
  build/kubevirt-web-ui-ansible/roles/kubevirt_web_ui/tasks/provision.yml
Labels: size/S

#31 Grant privileges to kube-public
  README.md
  deploy/crds/kubevirt_v1alpha1_kwebui_cr.yaml
  deploy/role.yaml
  deploy/role_binding_kube-public.yaml
  deploy/role_kube-public.yaml
Labels: size/M

#33 operator.yaml: use :latest tag
  deploy/operator.yaml
Labels: size/XS

#34 Fix missing service-ca
  build/kubevirt-web-ui-ansible/roles/kubevirt_web_ui/files/console-template.yaml
Labels: size/XS
