Repository kubevirt/web-ui-operator, pull requests merged in 2019-05, with the labels that each got.

#62 Set ansible inventory values from env variables
  pkg/components/components.go
  pkg/controller/kwebui/helper.go
  pkg/controller/kwebui/provision.go
Labels: size/M

#66 Move project under $GOPATH/src/github.com/kubevirt
  cmd/manager/main.go
  pkg/apis/addtoscheme_kubevirt_v1alpha1.go
  pkg/controller/add_kwebui.go
  pkg/controller/kwebui/kwebui_controller.go
  pkg/controller/kwebui/provision.go
Labels: size/S

#67 Synced by hack/make-olm.sh for 0.1.5
  deploy/olm-catalog/kubevirt-web-ui-operator/0.1.5/kubevirt-web-ui-operator.v0.1.5.clusterserviceversion.yaml
  deploy/olm-catalog/kubevirt-web-ui-operator/0.1.5/kubevirt_v1alpha1_kwebui_crd.yaml
  deploy/olm-catalog/kubevirt-web-ui-operator/kubevirt-web-ui-package.yaml
Labels: size/L

#68 Give web-ui-operator permission interact with pods at the Cluster scope
  pkg/components/components.go
Labels: size/XS

#69 Fix image name for missing "registry_namespace"
  build/kubevirt-web-ui-ansible/roles/kubevirt_web_ui/tasks/required_params.yml
Labels: size/XS

#70 Synced by hack/make-olm.sh for 0.1.6
  deploy/olm-catalog/kubevirt-web-ui-operator/0.1.6/kubevirt-web-ui-operator.v0.1.6.clusterserviceversion.yaml
  deploy/olm-catalog/kubevirt-web-ui-operator/0.1.6/kubevirt_v1alpha1_kwebui_crd.yaml
  deploy/olm-catalog/kubevirt-web-ui-operator/kubevirt-web-ui-package.yaml
Labels: size/L

#71 components.go: explicitely set WEBUI_TAG env var
  pkg/components/components.go
  pkg/controller/kwebui/provision.go
Labels: size/S

#73 Allign serviceAccount permissions
  pkg/components/components.go
Labels: size/S

#72 Introduce "Version: automatic"
  pkg/controller/kwebui/provision.go
Labels: size/M

#77 Fix deployment namespace
  build/kubevirt-web-ui-ansible/roles/kubevirt_web_ui/tasks/provision.yml
  cmd/manager/main.go
  pkg/components/components.go
  pkg/controller/kwebui/kwebui_controller.go
  pkg/controller/kwebui/provision.go
  vendor/github.com/operator-framework/operator-sdk/pkg/leader/leader.go
Labels: size/M

#78 Synced by hack/make-olm.sh for 0.1.10
  deploy/olm-catalog/kubevirt-web-ui-operator/0.1.10/kubevirt-web-ui-operator.v0.1.10.clusterserviceversion.yaml
  deploy/olm-catalog/kubevirt-web-ui-operator/0.1.10/kubevirt_v1alpha1_kwebui_crd.yaml
  deploy/olm-catalog/kubevirt-web-ui-operator/kubevirt-web-ui-package.yaml
Labels: size/L

#79 Align static role.yaml with components.go
  deploy/crds/kubevirt_v1alpha1_kwebui_cr.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  pkg/components/components.go
Labels: size/M

#84 Prevent deadlock for rolling update
  cmd/manager/main.go
Labels: size/XS

#87 build.sh: allow branches
  build.sh
Labels: size/XS
