Repository kubevirt/web-ui-operator, pull requests merged in 2019-04, with the labels that each got.

#40 Use 'Always' as default imagePullPolicy
  deploy/crds/kubevirt_v1alpha1_kwebui_cr.yaml
Labels: size/XS

#42 Avoid "oc adm policy add-scc-to-user anyuid" in install instructions
  README.md
  build/Dockerfile
  deploy/operator.yaml
  deploy/scc_anyuid.yaml
  hack/deploy
  hack/undeploy
Labels: size/M

#39 Initial deploy/README.md
  deploy/README.md
Labels: size/XS

#43 Don't run operator as root
  build/Dockerfile
  build/entrypoint.sh
  deploy/operator.yaml
  pkg/controller/kwebui/provision.go
Labels: size/M

#44 SCC anyuid removed
  README.md
  deploy/scc_anyuid.yaml
  hack/deploy
Labels: size/S

#45 Remove namespace from service_ca
  build/kubevirt-web-ui-ansible/roles/kubevirt_web_ui/files/service_ca_config.yaml
Labels: size/XS

#46 Replace namespaced roles with cluster role
  README.md
  deploy/role.yaml
  deploy/role_binding_extra_for_console.yaml
  deploy/role_binding_kube-public.yaml
  deploy/role_extra_for_console.yaml
  deploy/role_kube-public.yaml
Labels: size/M

#47 Increase number of replicas to 2
  build/kubevirt-web-ui-ansible/roles/kubevirt_web_ui/defaults/main.yml
Labels: size/XS

#49 build.sh: bump v0.1.1
  build.sh
Labels: size/XS

#48 Generate CSV for KubeVirt Web UI Operator
  deploy/olm-catalog/kubevirt-web-ui-operator/0.1.1/kubevirt-web-ui-operator.v0.1.1.clusterserviceversion.yaml
  deploy/olm-catalog/kubevirt-web-ui-operator/0.1.1/kubevirt_v1alpha1_kwebui_crd.yaml
  deploy/olm-catalog/kubevirt-web-ui-operator/kubevirt-web-ui-package.yaml
  hack/make-olm.sh
  hack/update-olm.py
Labels: size/L

#51 Fix setting of env vars
  build.sh
Labels: size/XS

#60 ConfigMap: set registry and V2V image tag
  build/kubevirt-web-ui-ansible/roles/kubevirt_web_ui/files/console-config.yaml
  build/kubevirt-web-ui-ansible/roles/kubevirt_web_ui/tasks/console-config.yml
Labels: size/S

#58 Grant cluster-wide kubevirt.io API access to operator's SA
  pkg/components/components.go
Labels: size/XS
